### ISSUE TITLE
簡単なLinuxコマンドを覚える  part2

### ISSUE THREAD

**Issue by RVIRUS0817** [Ayana0423/menta#4]
## 要件

以下の課題をこなしてください

- ホームディレクトリにPracticeディレクトリを作成
- Practiceディレクトリの中にcommandディレクトリを作成
- commandディレクトリはどこにあるのかあるコマンドを使ってパスを書いてください
- commandディレクトリにtest.txtを作成し、以下のように文字を追加する
```
vimのテスト

テスト
テスト
テスト
x 10
```
- test.txtが保存されているか表示してください
- 最後にtest.txtの削除

**Comment by Ayana0423** [comment]
- ホームディレクトリにPracticeディレクトリを作成
~~~
takahashiayana@MacBook-Pro ~ % mkdir practice
~~~

- Practiceディレクトリの中にcommandディレクトリを作成
~~~
takahashiayana@MacBook-Pro command % mkdir practice command
~~~

- commandディレクトリはどこにあるのかあるコマンドを使ってパスを書いてください
~~~
/Users/takahashiayana/practice/command
takahashiayana@MacBook-Pro command %
~~~

- commandディレクトリにtest.txtを作成し、以下のように文字を追加する
~~~
takahashiayana@MacBook-Pro command % vim test.txt
~~~
「i」挿入し記載「esc」→「:w」→「:q」ターミナルに戻る
~~~
takahashiayana@MacBook-Pro command % vim cat
takahashiayana@MacBook-Pro command % cat test.txt
vimのテスト

テスト
テスト
テスト
x 10成
~~~

- 最後にtest.txtの削除
~~~
takahashiayana@MacBook-Pro command % rm test.txt
takahashiayana@MacBook-Pro command % ls
~~~

**Comment by RVIRUS0817** [comment]
@Ayana0423 
OK！！

この `x 10` は `テスト` を10個書いてほしいということ
```
テスト
テスト
テスト
x 10
```

クローズします
